CREATE TABLE homework_DB (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	commands TEXT NOT NULL
);
INSERT INTO homework_DB (commands) VALUES ('CREATE TABLE'), ('PRIMARY KEY'),('NOT NULL'),('INTEGER'),('TEXT'),('INSERT'),('INTO'),('VALUES');