print("#"*9)
print("#", end="\t"*2)
print("#")
print("#", end="\t"*2)
print("#")
print("#", end="\t"*2)
print("#")
print("#"*9)
print()
print("#", end="\t\t")
print("#")
print("#", end="\t\t")
print("#")
print("#########")
print("#", end="\t\t")
print("#")
print("#", end="\t\t")
print("#")